flaskbook/apps/crud/models.py
from datetime import datetime

from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    __tablename__ = "users"
    
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String, index = True)
    email = db.Column(db.String, unique = True, index = True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default = datetime.now)
    updated_at = db.Column(db.DateTime, default = datetime.now, onupdate = datetime.now)
    user_images = db.relationship("UserImage", backref = "user", order_by="desc(UserImage.id)")
    
    @property
    def password(self):
        raise AttributeError("reading error")
    
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
        
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def is_duplicate_email(self):
        return User.query.filter_by(email = self.email).first() is not None
    
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)
        

flaskbook/apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length


# ユーザー新規作成とユーザー編集フォームクラス
class UserForm(FlaskForm):
    # ユーザーフォームのusername属性のラベルとバリデータを設定する
    username = StringField(
        "username",
        validators=[
            DataRequired(message="need username"),
            length(max=30, message="under 30"),
        ],
    )

    # ユーザーフォームemail属性のラベルとバリデータを設定する
    email = StringField(
        "mail",
        validators=[
            DataRequired(message="need mail"),
            Email(message="xxx@yyy"),
        ],
    )

    # ユーザーフォームpassword属性のラベルとバリデータを設定する
    password = PasswordField("password", validators=[DataRequired(message="need password")])

    # ユーザーフォームsubmitの文言を設定する
    submit = SubmitField("register new")

flaskbook/apps/crud/__init__.py
import apps.crud.models

flaskbook/apps/crud/views.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required
from apps.crud.forms import UserForm
from apps.app import db
from apps.crud.models import User

crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)

@crud.route("/")
@login_required
def index():
    return render_template("crud/index.html")

@crud.route("/sql")
@login_required
def sql():
    db.session.query(User).all()
    return "check console log"

@crud.route("/users")
@login_required
def users():
    users = User.query.all()
    return render_template("crud/index.html", users = users)

@crud.route("/users/new", methods = ["GET", "POST"])
@login_required
def create_user():
    form = UserForm()
    if form.validate_on_submit():
        user = User(
            username = form.username.data,
            email = form.email.data,
            password = form.password.data
        )
        
        db.session.add(user)
        db.session.commit()
        
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form = form)

@crud.route("/users/<user_id>", methods = ["GET", "POST"])
@login_required
def edit_user(user_id):
    form = UserForm()
    
    user = User.query.filter_by(id = user_id).first()
    
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template("crud/edit.html", user = user, form = form)

@crud.route("/users/<user_id>/delete", methods = ["POST"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id = user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

flaskbook/apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <!-- titleを継承先で実装する -->
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css' ) }}" />
</head>

<body>
    <div>
        {% if current_user.is_authenticated %}
        <p>
            <span>{{ current_user.username }}</span> -
            <span><a href="{{ url_for('auth.logout') }}">logout</a></span>
        </p>
        {% endif %}
    </div>
    <!-- contentを継承先で実装する -->
    {% block content %}{% endblock %}
</body>
</html>

flaskbook/apps/crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title %}create new user{% endblock %}
{% block content %}
<h2>create new user</h2>
<form action="{{ url_for('crud.create_user') }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(placeholder="username") }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.email.label }} {{ form.email(placeholder="mail") }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label }} {{ form.password(placeholder="password") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

flaskbook/apps/crud/templates/crud/edit.html
{% extends 'crud/base.html' %}
{% block title %}edit user{% endblock %}
{% block content %}
<h2>edit user</h2>
<form action="{{ url_for('crud.edit_user', user_id=user.id) }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(placeholder="username",
        value=user.username) }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.email.label }} {{ form.email(placeholder="mail",
        value=user.email) }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label }} {{ form.password(placeholder="password") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p><input type="submit" value="apply" /></p>
</form>

<form action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="POST">
    {{ form.csrf_token }}
    <input type="submit" value="delete">
</form>
{% endblock %}

flaskbook/apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %}users{% endblock %}
{% block content %}
<h2>users</h2>
<a href="{{ url_for('crud.create_user') }}">new user</a>
<table>
    <tr>
        <th>userid</th>
        <th>username</th>
        <th>mail</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>
            <a href="{{ url_for('crud.edit_user', user_id=user.id) }}">{{ user.id }}</a>
        </td>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}